AWSTemplateFormatVersion: 2010-09-09
Resources:             

  HelloLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CilLambdaFunction
      Role: arn:aws:iam::614319693978:role/lambdaRole
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
            return message


  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket in CloudFormation
    Properties:
      BucketName: cil-internship-bucket
